// Generated by scripts/build_architectures.py. Do not edit.
const EMTR_ARCHITECTURES = {
  "0": {
    "name": "Thumb",
    "bits": 32,
    "endian": "little",
    "family": "arm",
    "sp": "SP",
    "pc": "PC",
    "flags": "CPSR",
    "csArch": "ARM",
    "csModes": [
      "THUMB"
    ]
  },
  "1": {
    "name": "ARM32",
    "bits": 32,
    "endian": "little",
    "family": "arm",
    "sp": "SP",
    "pc": "PC",
    "flags": "CPSR",
    "csArch": "ARM",
    "csModes": [
      "ARM"
    ]
  },
  "2": {
    "name": "AArch64",
    "bits": 64,
    "endian": "little",
    "family": "arm64",
    "sp": "SP",
    "pc": "PC",
    "flags": "NZCV",
    "csArch": "ARM64",
    "csModes": []
  },
  "3": {
    "name": "x86",
    "bits": 32,
    "endian": "little",
    "family": "x86",
    "sp": "ESP",
    "pc": "EIP",
    "flags": "EFLAGS",
    "csArch": "X86",
    "csModes": [
      "32"
    ]
  },
  "4": {
    "name": "x86-64",
    "bits": 64,
    "endian": "little",
    "family": "x86",
    "sp": "RSP",
    "pc": "RIP",
    "flags": "EFLAGS",
    "csArch": "X86",
    "csModes": [
      "64"
    ]
  },
  "5": {
    "name": "MIPS32 \u00b7 BE",
    "bits": 32,
    "endian": "big",
    "family": "mips",
    "sp": "sp",
    "pc": "PC",
    "flags": "",
    "csArch": "MIPS",
    "csModes": [
      "MIPS32",
      "BIG_ENDIAN"
    ]
  },
  "6": {
    "name": "MIPS32 \u00b7 LE",
    "bits": 32,
    "endian": "little",
    "family": "mips",
    "sp": "sp",
    "pc": "PC",
    "flags": "",
    "csArch": "MIPS",
    "csModes": [
      "MIPS32"
    ]
  },
  "7": {
    "name": "MIPS64 \u00b7 BE",
    "bits": 64,
    "endian": "big",
    "family": "mips",
    "sp": "sp",
    "pc": "PC",
    "flags": "",
    "csArch": "MIPS",
    "csModes": [
      "MIPS64",
      "BIG_ENDIAN"
    ]
  },
  "8": {
    "name": "MIPS64 \u00b7 LE",
    "bits": 64,
    "endian": "little",
    "family": "mips",
    "sp": "sp",
    "pc": "PC",
    "flags": "",
    "csArch": "MIPS",
    "csModes": [
      "MIPS64"
    ]
  },
  "9": {
    "name": "x86 \u00b7 16-bit",
    "bits": 16,
    "endian": "little",
    "family": "x86",
    "sp": "SP",
    "pc": "IP",
    "flags": "EFLAGS",
    "csArch": "X86",
    "csModes": [
      "16"
    ]
  },
  "10": {
    "name": "PowerPC32",
    "bits": 32,
    "endian": "big",
    "family": "ppc",
    "sp": "R1",
    "pc": "PC",
    "flags": "CR",
    "csArch": "PPC",
    "csModes": [
      "32",
      "BIG_ENDIAN"
    ]
  },
  "11": {
    "name": "PowerPC64",
    "bits": 64,
    "endian": "big",
    "family": "ppc",
    "sp": "R1",
    "pc": "PC",
    "flags": "CR",
    "csArch": "PPC",
    "csModes": [
      "64",
      "BIG_ENDIAN"
    ]
  },
  "12": {
    "name": "SPARC32",
    "bits": 32,
    "endian": "big",
    "family": "sparc",
    "sp": "O6",
    "pc": "PC",
    "flags": "",
    "csArch": "SPARC",
    "csModes": [
      "BIG_ENDIAN"
    ]
  },
  "13": {
    "name": "SPARC64",
    "bits": 64,
    "endian": "big",
    "family": "sparc",
    "sp": "O6",
    "pc": "PC",
    "flags": "",
    "csArch": "SPARC",
    "csModes": [
      "V9",
      "BIG_ENDIAN"
    ]
  },
  "14": {
    "name": "Motorola 68000",
    "bits": 32,
    "endian": "big",
    "family": "m68k",
    "sp": "A7",
    "pc": "PC",
    "flags": "SR",
    "csArch": "M68K",
    "csModes": [
      "M68K_000",
      "BIG_ENDIAN"
    ]
  },
  "15": {
    "name": "RISC-V32",
    "bits": 32,
    "endian": "little",
    "family": "riscv",
    "sp": "X2",
    "pc": "PC",
    "flags": "",
    "csArch": "RISCV",
    "csModes": [
      "RISCV32",
      "RISCVC"
    ]
  },
  "16": {
    "name": "RISC-V64",
    "bits": 64,
    "endian": "little",
    "family": "riscv",
    "sp": "X2",
    "pc": "PC",
    "flags": "",
    "csArch": "RISCV",
    "csModes": [
      "RISCV64",
      "RISCVC"
    ]
  },
  "17": {
    "name": "S390X / SystemZ",
    "bits": 64,
    "endian": "big",
    "family": "s390x",
    "sp": "R15",
    "pc": "PC",
    "flags": "PSWM",
    "csArch": "SYSZ",
    "csModes": [
      "BIG_ENDIAN"
    ]
  },
  "18": {
    "name": "TriCore",
    "bits": 32,
    "endian": "little",
    "family": "tricore",
    "sp": "A10",
    "pc": "PC",
    "flags": "PSW",
    "csArch": "TRICORE",
    "csModes": [
      "TRICORE_162"
    ]
  },
  "19": {
    "name": "Thumb \u00b7 BE",
    "bits": 32,
    "endian": "big",
    "family": "arm",
    "sp": "SP",
    "pc": "PC",
    "flags": "CPSR",
    "csArch": "ARM",
    "csModes": [
      "THUMB",
      "BIG_ENDIAN"
    ]
  },
  "20": {
    "name": "ARM32 \u00b7 BE",
    "bits": 32,
    "endian": "big",
    "family": "arm",
    "sp": "SP",
    "pc": "PC",
    "flags": "CPSR",
    "csArch": "ARM",
    "csModes": [
      "ARM",
      "BIG_ENDIAN"
    ]
  },
  "21": {
    "name": "AArch64 \u00b7 BE",
    "bits": 64,
    "endian": "big",
    "family": "arm64",
    "sp": "SP",
    "pc": "PC",
    "flags": "NZCV",
    "csArch": "ARM64",
    "csModes": [
      "BIG_ENDIAN"
    ]
  },
  "22": {
    "name": "ARM Cortex-M",
    "bits": 32,
    "endian": "little",
    "family": "arm",
    "sp": "SP",
    "pc": "PC",
    "flags": "XPSR",
    "csArch": "ARM",
    "csModes": [
      "THUMB",
      "MCLASS"
    ]
  }
};
if (typeof module !== 'undefined') module.exports = EMTR_ARCHITECTURES;
