"""Generate the browser registry from the Python source of truth."""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from architectures import ARCHITECTURES


def render():
    entries = {
        int(a): dict(
            name=s.name,
            bits=s.bits,
            endian=s.endian,
            family=s.family,
            sp=s.sp,
            pc=s.pc,
            flags=s.flags,
            csArch=s.cs_arch,
            csModes=list(s.cs_modes),
        )
        for a, s in ARCHITECTURES.items()
    }
    return (
        "// Generated by scripts/build_architectures.py. Do not edit.\n"
        + "const EMTR_ARCHITECTURES = "
        + json.dumps(entries, indent=2)
        + ";\n"
        + "if (typeof module !== 'undefined') module.exports = EMTR_ARCHITECTURES;\n"
    )


if __name__ == "__main__":
    Path(__file__).resolve().parents[1].joinpath("emu_architectures.js").write_text(render())
