"""Rebuild the offline demo using a real x86-64 emulation run."""

import base64
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from example_trace import make_trace  # noqa: E402

if __name__ == "__main__":
    data = make_trace().dump()
    (ROOT / "examples" / "trace_x86_64.emtr").write_bytes(data)
    (ROOT / "demo_trace.js").write_text(
        "// Generated by scripts/build_demo.py from real Unicorn execution.\n"
        + "const DEMO_TRACE_BASE64 = "
        + repr(base64.b64encode(data).decode("ascii"))
        + ";\n"
    )
